FROM node:20.12-alpine

WORKDIR /app

COPY package.json ./
COPY package-lock.json ./
RUN npm ci

COPY . .

RUN ["npm", "run", "build"]

EXPOSE 4173

CMD ["npm", "run", "preview", "--", "--host", "--port", "4173"]
